name: saltstack-nginx-formula
source: https://github.com/bechtoldt/saltstack-nginx-formula
summary: SaltStack Formula to set up and configure nginx, a HTTP and reverse proxy server
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - manage nginx.conf (I need to set server_names_hash_bucket_size=64)
